language: python
python:
  - 3.3
  - 3.4

services:
  - couchdb

install:
  - make dev

script:
  - make check
  - make docs

env:
  matrix:
    - PYTHONASYNCIODEBUG=0
      AIOCOUCHDB_TARGET=mock
    - PYTHONASYNCIODEBUG=1
      AIOCOUCHDB_TARGET=mock
    - PYTHONASYNCIODEBUG=0
      AIOCOUCHDB_TARGET=couchdb
    - PYTHONASYNCIODEBUG=1
      AIOCOUCHDB_TARGET=couchdb
